[package]
name = "llama-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llama-sys = { git = "https://github.com/shadowmint/llama-sys.git", tag = "1.0.0" }
